# Generated by Django 3.2 on 2022-10-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('category', models.CharField(choices=[('AN', 'Разное'), ('CP', 'Компьютеры'), ('SM', 'Смартфоны'), ('CL', 'Одежда')], default='AN', max_length=2)),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание товара')),
                ('image', models.ImageField(null=True, upload_to='images')),
            ],
        ),
    ]
