# Generated by Django 3.2 on 2022-10-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True, max_length=300, verbose_name='Текст отзыва'),
        ),
    ]
