# Generated by Django 3.2 on 2022-10-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20221029_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='media/images/empty.jpg', null=True, upload_to='media/images', verbose_name='Изображение'),
        ),
    ]
