# Generated by Django 3.2 on 2022-10-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_review_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='uploads/images/empty.jpg', null=True, upload_to='uploads/images', verbose_name='Изображение'),
        ),
    ]
